---
apiVersion: v1
kind: Secret
metadata:
  name: chri5p-chri5p-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/chri5p-gateway-gitops
